#ifndef OTHER_H
#define OTHER_H

enum Species {NONE, ELEPHANT, GIRAFFE, LION, TIGER, ORANGUTAN, CHIMPANZEE, KOMODO, BEAR, WHALE, DOLPHIN, CLOWNFISH, BLUETANG, PIRANHA, PUFFFISH, EAGLE, CENDRAWASIH, OWL, BAT, MACAU, COCKATOO, FROG, ALLIGATOR, HIPPOPOTAMUS, TURTLE};
enum Sex {MALE, FEMALE};
enum Color {RED, ORANGE, YELLOW, GREEN, BLUE, MAGENTA, CYAN, WHITE};
enum Habitat {LANDANIMAL, WATERANIMAL, FLYINGANIMAL, AMPHIBIAN};
enum Place {LANDHABITAT, WATERHABITAT, AIRHABITAT, RESTAURANT, PARK, ROAD, ENTRANCE, EXIT, PLACE_NONE};

#endif
